from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("books/", views.book_list, name="book_list"),
    path("books/<int:pk>/", views.book_detail, name="book_detail"),
    path("categories/", views.category_list, name="category_list"),
    path("categories/<int:pk>/", views.category_detail, name="category_detail"),
    path("register/", views.register, name="register"),
    path("cart/", views.cart_view, name="cart"),
    path("cart/add/<int:book_id>/", views.add_to_cart, name="add_to_cart"),
    path("cart/update/", views.update_cart, name="update_cart"),
    path("cart/remove/<int:book_id>/", views.remove_from_cart, name="remove_from_cart"),
    path("checkout/", views.checkout, name="checkout"),
    path("api/v1/coupon/apply/", views.api_apply_coupon, name="api_apply_coupon"),
    path("orders/", views.order_list, name="order_list"),
    path("orders/<int:pk>/", views.order_detail, name="order_detail"),
    path("orders/<int:pk>/payment/", views.payment_gateway, name="payment_gateway"),
    path("orders/payment/vnpay-return/", views.vnpay_return, name="vnpay_return"),
    path("orders/<int:pk>/payment/confirm/", views.payment_confirm, name="payment_confirm"),
    path("orders/<int:pk>/cancel/", views.cancel_order, name="cancel_order"),
    path("rate/<int:book_id>/", views.rate_book, name="rate_book"),
    path("wishlist/", views.wishlist_view, name="wishlist"),
    path("wishlist/add/<int:book_id>/", views.wishlist_add, name="wishlist_add"),
    path("wishlist/remove/<int:book_id>/", views.wishlist_remove, name="wishlist_remove"),
    path("profile/", views.profile, name="profile"),
    path("profile/edit/", views.profile_edit, name="profile_edit"),
    path("profile/reading-dna/", views.reading_dna, name="reading_dna"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    # Admin dashboard
    path("dashboard/", views.dashboard, name="dashboard"),
    path("dashboard/export/orders/", views.export_orders_csv, name="export_orders_csv"),
    path("dashboard/export/books/", views.export_books_csv, name="export_books_csv"),
    path("dashboard/order/<int:pk>/status/", views.api_update_order_status, name="api_update_order_status"),
    # REST API
    path("api/search/", views.api_search, name="api_search"),
    path("api/v1/books/", views.api_books, name="api_books"),
    path("api/v1/books/<int:pk>/", views.api_book_detail, name="api_book_detail"),
    path("api/v1/stats/", views.api_stats, name="api_stats"),
    path("api/v1/chatbot/", views.api_chatbot, name="api_chatbot"),
    path("api/v1/chatbot/stream/", views.api_chatbot_stream, name="api_chatbot_stream"),
]
